# Generated by Django 3.1.5 on 2021-02-18 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('image', models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth(mm/dd/yyyy) ')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('telephone_number', models.CharField(max_length=15)),
                ('cell_number', models.CharField(max_length=15)),
                ('permanent_address', models.TextField(blank=True, max_length=200, null=True)),
                ('permanent_telephone_number', models.CharField(max_length=15)),
                ('roles', models.CharField(choices=[('staff', 'STAFF'), ('business_unit', 'BUSINESS UNIT'), ('student', 'STUDENT'), ('visitor', 'VISITOR')], default='visitor', max_length=15)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('group', models.CharField(max_length=150)),
                ('next_of_kin_name', models.CharField(max_length=50)),
                ('next_of_kin_relationship', models.CharField(max_length=50)),
                ('next_of_kin_contact_number', models.CharField(max_length=15)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifeChoicesMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.IntegerField(null=True)),
                ('chronic_condition', models.CharField(max_length=50, null=True)),
                ('allergies', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifeChoicesStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('account_holder_name', models.CharField(max_length=50, null=True)),
                ('account_number', models.CharField(max_length=50, null=True)),
                ('branch_name', models.CharField(max_length=50, null=True)),
                ('branch_number', models.CharField(max_length=50, null=True)),
                ('WorkPermit_number', models.CharField(max_length=25, null=True)),
                ('tax_number', models.CharField(max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.lifechoicesmember')),
            ],
        ),
        migrations.CreateModel(
            name='LifeChoicesAcademy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=13, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.lifechoicesmember')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Family Leave', 'Family Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Study Leave', 'Study Leave'), ('Compensation Leave', 'Compensation Leave'), ('Other Leave', 'Other Leave')], max_length=45)),
                ('pre_authorisation', models.BooleanField(default=False)),
                ('personal_message', models.CharField(blank=True, max_length=200, null=True)),
                ('leave_date_from', models.DateField()),
                ('leave_date_to', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.lifechoicesstuff')),
            ],
        ),
        migrations.CreateModel(
            name='CovidQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Shortness_of_breath', models.BooleanField(default=True)),
                ('sore_throat', models.BooleanField(default=True)),
                ('loss_of_taste_or_smell', models.BooleanField(default=True)),
                ('contact_with_Covid', models.BooleanField(default=True)),
                ('nasal_congestion', models.BooleanField(default=True)),
                ('diarrhea', models.BooleanField(default=True)),
                ('nausea', models.BooleanField(default=True)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
