# Generated by Django 3.1.5 on 2021-03-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
