# Generated by Django 3.1.5 on 2021-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifechoicesmember',
            name='ID_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
