# Generated by Django 3.1.5 on 2021-02-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankingdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('account_holder_name', models.CharField(max_length=50, null=True)),
                ('account_number', models.CharField(max_length=50, null=True)),
                ('branch_name', models.CharField(max_length=50, null=True)),
                ('branch_number', models.CharField(max_length=50, null=True)),
                ('tax_number', models.CharField(max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.lifechoicesmember')),
            ],
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.lifechoicesmember'),
        ),
        migrations.DeleteModel(
            name='LifeChoicesStuff',
        ),
    ]
