# Generated by Django 3.1.5 on 2021-02-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_auto_20210222_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bankingdetails',
            new_name='BankingDetail',
        ),
    ]
