# Generated by Django 3.1.5 on 2021-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_auto_20210210_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifechoicesmember',
            name='ID_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lifechoicesmember',
            name='allergies',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lifechoicesmember',
            name='chronic_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
